"""Generate css/pf-header.css: v3's own header rules, scoped under .pf-header-host.

Companion to gen-pf-footer.py, and it borrows that file's scoper rather than
keeping a second copy. Run from portfolio_v4's root.
"""
import re, pathlib, importlib.util

ns = {}
exec(pathlib.Path("scripts/gen-pf-footer.py").read_text().split("styles = pathlib.Path")[0], ns)
scope = ns["scope"]
SCOPE = ".pf-header-host"

styles = pathlib.Path("css/styles.css").read_text()
chrome = pathlib.Path("css/chrome.css").read_text()

m = re.search(r"/\* =+\n   HEADER\n   =+ \*/(.*?)(?=/\* =+\n   DIVIDERS)", styles, re.S)
assert m, "header block not found in styles.css"
header_block = m.group(1)

mr = re.search(r":root \{(.*?)\n\}", styles, re.S)
root_tokens = "\n".join(l for l in mr.group(1).splitlines() if "font-synthesis" not in l)

active = ".nav__link.is-active::after { transform: scaleX(1); }"
assert active in chrome

HEADER = '''/* ============================================================================
   THE SITE HEADER, for pages that do not load v3's global stylesheets
   ----------------------------------------------------------------------------
   The companion to pf-footer.css, built the same way and for the same reason:
   the Sinan page cannot load v3's styles.css, whose global reset would restyle
   a page that was hand-built around its own. So v3's own HEADER block is scoped
   under .pf-header-host instead, with the tokens it reads redeclared there.

   The scope class goes on a WRAPPER, never on .header itself -- every rule below
   is scoped as a DESCENDANT, and a descendant selector does not match the
   element carrying the class.

   GENERATED by scripts/gen-pf-header.py from css/styles.css and css/chrome.css.
   Regenerate rather than hand-editing.
   ========================================================================== */
%s {
%s

  /* from styles.css's body rule, which the header inherits from on v3 */
  font-family: "Figtree", system-ui, -apple-system, "Segoe UI", sans-serif;
  color: var(--ink);
  line-height: 1.2;
  letter-spacing: -0.01em;
  -webkit-font-smoothing: antialiased;
}
%s *,
%s *::before,
%s *::after { box-sizing: border-box; }
%s * { margin: 0; padding: 0; }
%s img { display: block; max-width: 100%%; }
%s a { color: inherit; text-decoration: none; }
%s ul { list-style: none; }

/* ---- styles.css: .container ---- */
''' % ((SCOPE, root_tokens) + (SCOPE,) * 7)


def rescope(css):
    return scope(css).replace(".pf-footer-host", SCOPE)


mc = re.search(r"\.container \{.*?\n\}", styles, re.S)
out = (HEADER + rescope(mc.group(0))
       + "\n\n/* ==== styles.css: HEADER ================================================= */\n"
       + rescope(header_block)
       + "\n\n/* ==== chrome.css: the current page, in the nav =========================== */\n"
       + rescope(active) + "\n")
out = re.sub(r"\*/(?=\.pf-header-host)", "*/\n", out)
out = re.sub(r"\}(?=\.pf-header-host)", "}\n", out)
out = re.sub(r"\}(?=@)", "}\n", out)
out = re.sub(r"\n{4,}", "\n\n\n", out)
pathlib.Path("css/pf-header.css").write_text(out)
print("pf-header.css written:", len(out), "bytes")
