#!/usr/bin/env python3
"""
Write the master-suggestion section into every page that carries it.

Amanda: "add 'suggested projects' section... This is gonna be a master
component, called 'master-suggestion'... Just suggest 3 projects per page. So
basically the priority are: 1. Hazen, 2. Identity, 3. Aspire, 4. Nobi... put it
in all case study pages, just before the master footer... Please also put
master-suggestion in the 4 live pages' the-process sections. Put it just before
the master footer as well."

ELEVEN COPIES OF ONE COMPONENT is exactly the case for generating it: the roster
below is the only place the priority order lives, and re-running this updates
every page at once. It is idempotent -- an existing section is replaced, so this
can be run as often as the roster changes.

    python3 scripts/gen-master-suggestion.py

Each page shows the first three of PRIORITY that are not the page itself, unless
OVERRIDE names that page explicitly. Kayn sits outside PRIORITY, so the rule
alone would never surface it -- the HAZEN page is where Amanda asked for it, and
that is the one override.
"""
import io
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent

# The roster, in Amanda's order.
PRIORITY = ["hazen", "identity", "aspire", "nobi"]

PROJECTS = {
    "hazen":    dict(href="/project_hazen/",    title="Claude design skills: HAZEN",
                     tags=["Claude Skills"]),
    "identity": dict(href="/project_identity/", title="Identity 2.0",
                     tags=["Brand Design", "Web Design"]),
    "aspire":   dict(href="/project_aspire/",   title="Aspire Web Design System",
                     tags=["Web Design", "Web Design System"]),
    "nobi":     dict(href="/project_nobi/",     title="NOBI Bakery",
                     tags=["Brand Design", "Web Design"]),
    "kayn":     dict(href="/project_kayn/",     title="Kayn Argan Oil",
                     tags=["Brand Design", "Web Design"]),
}

# Amanda: "Please also add master-suggestion to sinan casestudy page as well. So
# Kayn will be suggested here." Strict priority would give the HAZEN page
# identity, aspire and nobi -- Kayn is below all three and would never surface
# anywhere, since only the page's own project is ever excluded. Her instruction
# for this one page wins over the ordering, so the lowest-priority pick makes
# way for Kayn and the rule is left alone everywhere else.
OVERRIDE = {
    "project_hazen/index.html": ["identity", "aspire", "kayn"],
}

# page -> the project it IS, so it never suggests itself. None where the page
# belongs to no project in the roster.
PAGES = {
    "project_aspire/casestudy/index.html":   "aspire",
    "project_identity/casestudy/index.html": "identity",
    "project_kayn/casestudy/index.html":     "kayn",
    "project_nobi/casestudy/index.html":     "nobi",
    "project_atlasique/index.html":          None,
    "project_bacarita/index.html":           None,
    "project_visuallab/index.html":          None,
    "project_aspire/index.html":             "aspire",
    "project_identity/index.html":           "identity",
    "project_kayn/index.html":               "kayn",
    "project_nobi/index.html":               "nobi",
    "project_hazen/index.html":              "hazen",
}

BEGIN = "<!-- BEGIN master-suggestion (generated by scripts/gen-master-suggestion.py) -->"
END = "<!-- END master-suggestion -->"

FOOTER_ANCHOR = "<!-- THE SITE FOOTER"


def card(key, indent):
    p = PROJECTS[key]
    pad = " " * indent
    tags = "".join(
        '<span class="msug__tag">%s</span>' % t for t in p["tags"]
    )
    return (
        '%s<li class="msug__item">\n'
        '%s  <a class="msug__card" href="%s" data-cursor="See project">\n'
        '%s    <span class="msug__media thumb thumb--%s">\n'
        '%s      <video class="msug__video" src="/images/thumbnail_%s.webm"\n'
        '%s             poster="/images/thumbnail_%s_poster.webp"\n'
        '%s             preload="none" muted playsinline\n'
        '%s             disablepictureinpicture disableremoteplayback aria-hidden="true"></video>\n'
        '%s    </span>\n'
        '%s    <span class="msug__title">%s</span>\n'
        '%s    <span class="msug__tags">%s</span>\n'
        '%s  </a>\n'
        '%s</li>\n'
    ) % (pad, pad, p["href"], pad, key, pad, key, pad, key, pad, pad,
         pad, pad, p["title"], pad, tags, pad, pad)


def section(picks, indent):
    pad = " " * indent
    cards = "".join(card(k, indent + 4) for k in picks)
    return (
        "%s%s\n"
        '%s<section class="master-suggestion" aria-labelledby="msugHead">\n'
        '%s  <div class="msug__wrap">\n'
        '%s    <h2 class="msug__head" id="msugHead">See other projects</h2>\n'
        '%s    <ul class="msug__grid">\n'
        "%s"
        '%s    </ul>\n'
        '%s  </div>\n'
        '%s</section>\n'
        "%s%s\n\n"
    ) % (pad, BEGIN, pad, pad, pad, pad, cards, pad, pad, pad, pad, END)


def stylesheets(html):
    """Both sheets, once, next to the master-footer link the page already has."""
    for href in ("/css/master-thumb.css", "/css/master-suggestion.css"):
        if href in html:
            continue
        m = re.search(r'([ \t]*)<link rel="stylesheet" href="/css/master-footer\.css"[^>]*>\n', html)
        if not m:
            raise SystemExit("no master-footer link to anchor on")
        tag = '%s<link rel="stylesheet" href="%s"%s>\n' % (
            m.group(1), href, " /" if m.group(0).rstrip().endswith("/>") else "")
        html = html[: m.end()] + tag + html[m.end():]
    return html


def scripts(html):
    """The two behaviours, before </body>, once."""
    for src in ("/js/thumb-video.js", "/js/thumb-open.js"):
        if src in html:
            continue
        tag = '<script src="%s"></script>\n' % src
        i = html.rindex("</body>")
        html = html[:i] + tag + html[i:]
    return html


def main():
    for rel, own in PAGES.items():
        path = ROOT / rel
        html = io.open(path, encoding="utf-8").read()

        picks = OVERRIDE.get(rel) or [k for k in PRIORITY if k != own][:3]

        # replace an existing section, or insert before the footer
        block = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END) + r"\n*", re.S)
        existing = block.search(html)
        if existing:
            indent = len(html[: existing.start()].rsplit("\n", 1)[-1])
            html = block.sub(lambda _: section(picks, indent).lstrip()
                             if indent else section(picks, 0), html, count=1)
        else:
            i = html.index(FOOTER_ANCHOR)
            indent = len(html[:i].rsplit("\n", 1)[-1])
            html = html[: i - indent] + section(picks, indent) + html[i - indent:]

        html = stylesheets(html)
        html = scripts(html)
        io.open(path, "w", encoding="utf-8").write(html)
        print("%-42s %s" % (rel, " · ".join(picks)))


if __name__ == "__main__":
    main()
