#!/usr/bin/env python3
"""
Write the master-suggestion section into every page that carries it.

Amanda: "add 'suggested projects' section... This is gonna be a master
component, called 'master-suggestion'... Just suggest 3 projects per page. So
basically the priority are: 1. Hazen, 2. Identity, 3. Aspire, 4. Nobi... put it
in all case study pages, just before the master footer... Please also put
master-suggestion in the 4 live pages' the-process sections. Put it just before
the master footer as well."

ELEVEN COPIES OF ONE COMPONENT is exactly the case for generating it: the roster
below is the only place the priority order lives, and re-running this updates
every page at once. It is idempotent -- an existing section is replaced, so this
can be run as often as the roster changes.

    python3 scripts/gen-master-suggestion.py

Each page shows the first three of PRIORITY that are not the page itself. Kayn
sits outside PRIORITY and is therefore never suggested, which is deliberate.
"""
import io
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent

# The roster, in Amanda's order.
PRIORITY = ["hazen", "identity", "aspire", "nobi"]

PROJECTS = {
    "hazen":    dict(href="/project_hazen/",    title="Claude design skills: HAZEN",
                     tags=["Claude Skills"]),
    "identity": dict(href="/project_identity/", title="Identity 2.0",
                     tags=["Brand Design", "Web Design"]),
    "aspire":   dict(href="/project_aspire/",   title="Aspire Web Design System",
                     tags=["Web Design", "Web Design System"]),
    "nobi":     dict(href="/project_nobi/",     title="NOBI Bakery",
                     tags=["Brand Design", "Web Design"]),
    "kayn":     dict(href="/project_kayn/",     title="Kayn Argan Oil",
                     tags=["Brand Design", "Web Design"]),
}

# Kayn stays out of PRIORITY, and out of the suggestions entirely -- Amanda:
# "Please use nobi instead of kayn in Hazen's page. It's totally okay kayn left
# out." Its entry above is kept so the roster can be reordered without also
# having to re-describe the project. No page overrides its picks any more.
OVERRIDE = {}

# The one page that renames the section. Amanda: "Only for this page, the
# master-suggestion headline is 'See my work' which suits better."
HEADLINE = {
    "404.html": "See my work",
}
DEFAULT_HEADLINE = "See other projects"

# page -> the project it IS, so it never suggests itself. None where the page
# belongs to no project in the roster.
PAGES = {
    "project_aspire/casestudy/index.html":   "aspire",
    "project_identity/casestudy/index.html": "identity",
    "project_kayn/casestudy/index.html":     "kayn",
    "project_nobi/casestudy/index.html":     "nobi",
    "project_atlasique/index.html":          None,
    "project_bacarita/index.html":           None,
    "project_visuallab/index.html":          None,
    "project_aspire/index.html":             "aspire",
    "project_identity/index.html":           "identity",
    "project_kayn/index.html":               "kayn",
    "project_nobi/index.html":               "nobi",
    "project_hazen/index.html":              "hazen",
    "404.html":                              None,
}

BEGIN = "<!-- BEGIN master-suggestion (generated by scripts/gen-master-suggestion.py) -->"
END = "<!-- END master-suggestion -->"

# Where the section goes: immediately above whatever opens the footer. The
# project pages carry the scoped master-footer block and its banner comment;
# 404.html carries v3's own contact section, since it loads v3's stylesheets
# directly and needs no scoped copy.
FOOTER_ANCHORS = ("<!-- THE SITE FOOTER", "<!-- ===================== CONTACT")


def card(key, indent):
    p = PROJECTS[key]
    pad = " " * indent
    tags = "".join(
        '<span class="msug__tag">%s</span>' % t for t in p["tags"]
    )
    return (
        '%s<li class="msug__item">\n'
        '%s  <a class="msug__card" href="%s" data-cursor="See project">\n'
        '%s    <span class="msug__media thumb thumb--%s">\n'
        '%s      <video class="msug__video" src="/images/thumbnail_%s.webm"\n'
        '%s             poster="/images/thumbnail_%s_poster.webp"\n'
        '%s             preload="none" muted playsinline\n'
        '%s             disablepictureinpicture disableremoteplayback aria-hidden="true"></video>\n'
        '%s    </span>\n'
        '%s    <span class="msug__title">%s</span>\n'
        '%s    <span class="msug__tags">%s</span>\n'
        '%s  </a>\n'
        '%s</li>\n'
    ) % (pad, pad, p["href"], pad, key, pad, key, pad, key, pad, pad,
         pad, pad, p["title"], pad, tags, pad, pad)


def section(picks, indent, headline):
    pad = " " * indent
    cards = "".join(card(k, indent + 4) for k in picks)
    return (
        "%s%s\n"
        '%s<section class="master-suggestion" aria-labelledby="msugHead">\n'
        '%s  <div class="msug__wrap">\n'
        '%s    <h2 class="msug__head" id="msugHead">%s</h2>\n'
        '%s    <ul class="msug__grid">\n'
        "%s"
        '%s    </ul>\n'
        '%s  </div>\n'
        '%s</section>\n'
        "%s%s\n\n"
    ) % (pad, BEGIN, pad, pad, pad, headline, pad, cards, pad, pad, pad, pad, END)


def stylesheets(html):
    """Both sheets, once, next to the master-footer link the page already has."""
    for href in ("/css/master-thumb.css", "/css/master-suggestion.css"):
        if href in html:
            continue
        m = re.search(r'([ \t]*)<link rel="stylesheet" href="/css/master-footer\.css"[^>]*>\n', html)
        if not m:
            raise SystemExit("no master-footer link to anchor on")
        tag = '%s<link rel="stylesheet" href="%s"%s>\n' % (
            m.group(1), href, " /" if m.group(0).rstrip().endswith("/>") else "")
        html = html[: m.end()] + tag + html[m.end():]
    return html


def scripts(html):
    """The two behaviours, before </body>, once."""
    for src in ("/js/thumb-video.js", "/js/thumb-open.js"):
        if src in html:
            continue
        tag = '<script src="%s"></script>\n' % src
        i = html.rindex("</body>")
        html = html[:i] + tag + html[i:]
    return html


def main():
    for rel, own in PAGES.items():
        path = ROOT / rel
        html = io.open(path, encoding="utf-8").read()

        picks = OVERRIDE.get(rel) or [k for k in PRIORITY if k != own][:3]
        headline = HEADLINE.get(rel, DEFAULT_HEADLINE)

        # replace an existing section, or insert before the footer
        block = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END) + r"\n*", re.S)
        existing = block.search(html)
        if existing:
            indent = len(html[: existing.start()].rsplit("\n", 1)[-1])
            html = block.sub(lambda _: section(picks, indent, headline).lstrip()
                             if indent else section(picks, 0, headline), html, count=1)
        else:
            i = -1
            for anchor in FOOTER_ANCHORS:
                if anchor in html:
                    i = html.index(anchor)
                    break
            if i < 0:
                raise SystemExit("no footer anchor in " + rel)
            indent = len(html[:i].rsplit("\n", 1)[-1])
            html = html[: i - indent] + section(picks, indent, headline) + html[i - indent:]

        html = stylesheets(html)
        html = scripts(html)
        io.open(path, "w", encoding="utf-8").write(html)
        print("%-42s %s" % (rel, " · ".join(picks)))


if __name__ == "__main__":
    main()
