"""Generate css/pf-footer.css: v3's own footer rules, scoped under .pf-footer-host."""
import re, pathlib

SCOPE = ".pf-footer-host"

def split_top(css):
    """Yield (kind, text) chunks: ('raw', s) for comments/whitespace,
       ('rule', selector, body) and ('at', prelude, body) for blocks."""
    out, i, n = [], 0, len(css)
    buf = ""
    while i < n:
        if css.startswith("/*", i):
            j = css.find("*/", i + 2)
            j = n if j < 0 else j + 2
            buf += css[i:j]; i = j; continue
        if css[i] == "{":
            head = buf; buf = ""
            depth, j = 1, i + 1
            while j < n and depth:
                if css.startswith("/*", j):
                    k = css.find("*/", j + 2); j = n if k < 0 else k + 2; continue
                if css[j] == "{": depth += 1
                elif css[j] == "}": depth -= 1
                j += 1
            body = css[i + 1:j - 1]
            # everything in head before the last "real" break belongs to the previous chunk
            # GREEDY to the LAST "*/": a head can hold several comments, and a
            # selector can never contain "*/", so everything before the final
            # one is prose, not selector.
            m = re.search(r"(?s)\A(.*\*/)?(.*)\Z", head)
            lead, sel = (m.group(1) or ""), m.group(2)
            if lead: out.append(("raw", lead))
            sel = sel.strip()
            out.append(("at" if sel.startswith("@") else "rule", sel, body))
            i = j; continue
        buf += css[i]; i += 1
    if buf: out.append(("raw", buf))
    return out

def scope_selector(sel):
    parts = []
    for s in sel.split(","):
        s = s.strip()
        if not s: continue
        if s in (":root", "html", "body"):
            parts.append(SCOPE)
        elif s in ("*", "*::before", "*::after"):
            parts.append(SCOPE + " " + s)
        else:
            parts.append(SCOPE + " " + s)
    return ",\n".join(parts)

def scope(css, indent=""):
    out = []
    for chunk in split_top(css):
        if chunk[0] == "raw":
            out.append(chunk[1])
        elif chunk[0] == "at":
            prelude, body = chunk[1], chunk[2]
            if re.match(r"@(media|supports|layer|container)\b", prelude):
                out.append("\n" + prelude + " {" + scope(body) + "\n}\n")
            else:                      # @font-face, @keyframes, @import: leave alone
                out.append(prelude + " {" + body + "}")
        else:
            out.append(scope_selector(chunk[1]) + " {" + chunk[2] + "}")
    return "".join(out)

styles = pathlib.Path("css/styles.css").read_text()
types  = pathlib.Path("css/type-system.css").read_text()
chrome = pathlib.Path("css/chrome.css").read_text()

# --- the CONTACT + FOOTER block, banner comment to the next banner -----------
m = re.search(r"/\* =+\n   CONTACT \+ FOOTER\n   =+ \*/(.*?)(?=/\* =+\n   SCROLL REVEAL)", styles, re.S)
assert m, "contact block not found in styles.css"
contact_block = m.group(1)

# --- .container, which the footer markup wraps itself in ---------------------
mc = re.search(r"\.container \{.*?\n\}", styles, re.S)
assert mc, ".container not found"
container_rule = mc.group(0)

# --- chrome.css minus the .nav__link rule, which is header not footer --------
head, tail = chrome.split("/* ---- the current page, in the nav ----", 1)
_, tail = tail.split(".nav__link.is-active::after { transform: scaleX(1); }", 1)
chrome_body = head + tail

# --- the tokens the block reads, redeclared on the host ----------------------
mr = re.search(r":root \{(.*?)\n\}", styles, re.S)
root_tokens = "\n".join(l for l in mr.group(1).splitlines() if "font-synthesis" not in l)

HEADER = """/* ============================================================================
   THE SITE FOOTER, for pages that do not load v3's global stylesheets
   ----------------------------------------------------------------------------
   This is v3's own footer — the same rules from css/styles.css, css/type-system.css
   and css/chrome.css, not a re-creation. Amanda: "Why not just use the existing
   one to keep the consistency."

   The five project pages cannot load v3's styles.css: it carries a global reset
   and would restyle five hand-built pages. So the rules are scoped under
   .pf-footer-host instead, and the tokens they read are redeclared there rather
   than on :root. Same declarations, same measured numbers, no leakage.

   The blocks below are in v3's own load order — styles.css, then type-system.css,
   then chrome.css — because that order is what decides the winner between two
   equally specific single-class rules. .contact__email carries .t-h4, and
   type-system.css loading last is the only reason the type scale sizes it.

   GENERATED by scratchpad/gen_footer.py from those three files. Keep it in step
   with them: if v3's CONTACT + FOOTER block, type system or chrome.css changes,
   regenerate rather than hand-editing.
   ========================================================================== */
%s {
%s

  /* from styles.css's body rule — the footer inherits these from it on v3 */
  font-family: "Figtree", system-ui, -apple-system, "Segoe UI", sans-serif;
  color: var(--ink);
  line-height: 1.2;
  letter-spacing: -0.01em;
  -webkit-font-smoothing: antialiased;
  text-rendering: optimizeLegibility;
}

/* v3's reset, scoped. The host pages have their own; this makes the footer's
   boxes and margins v3's regardless of what theirs happens to zero. */
%s *,
%s *::before,
%s *::after { box-sizing: border-box; }
%s * { margin: 0; padding: 0; }
%s img { display: block; max-width: 100%%; }
%s a { color: inherit; text-decoration: none; }
%s ul { list-style: none; }

/* ---- styles.css: .container ---- */
""" % (SCOPE, root_tokens, SCOPE, SCOPE, SCOPE, SCOPE, SCOPE, SCOPE, SCOPE)

parts = [
    HEADER,
    scope(container_rule),
    "\n\n/* ==== styles.css: CONTACT + FOOTER ====================================== */\n",
    scope(contact_block),
    "\n\n/* ==== type-system.css, entire ============================================ */\n",
    scope(types),
    "\n\n/* ==== chrome.css, minus the header's .nav__link rule ===================== */\n",
    scope(chrome_body),
    "\n",
]
out = "".join(parts)
# --- light reflow: the scoper emits valid but run-together CSS -------------
out = re.sub(r"\*/(?=\.pf-footer-host)", "*/\n", out)
out = re.sub(r"\}(?=\.pf-footer-host)", "}\n", out)
out = re.sub(r"\}(?=@)", "}\n", out)
out = re.sub(r"\n{4,}", "\n\n\n", out)
pathlib.Path("css/pf-footer.css").write_text(out)
print("written:", pathlib.Path("css/pf-footer.css").stat().st_size, "bytes")
