#!/usr/bin/env python3
"""Generate css/master-footer.css and css/master-header.css.

Both are v3's own rules -- from css/styles.css, css/type-system.css and
css/chrome.css -- re-emitted under a scope class so they can load on the project
pages, which cannot take v3's global reset without restyling five hand-built
designs. Run from portfolio_v4's root:  python3 scripts/gen-master-chrome.py
"""
import sys, pathlib, re
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from master_scope import collect, scope, reflow

CSS = pathlib.Path("css")
styles = (CSS / "styles.css").read_text()
types = (CSS / "type-system.css").read_text()
chrome = (CSS / "chrome.css").read_text()

root_tokens = "\n".join(
    l for l in re.search(r":root \{(.*?)\n\}", styles, re.S).group(1).splitlines()
    if "font-synthesis" not in l)

RESET = """%(S)s *,
%(S)s *::before,
%(S)s *::after { box-sizing: border-box; }
%(S)s * { margin: 0; padding: 0; }
%(S)s img { display: block; max-width: 100%%; }
%(S)s a { color: inherit; text-decoration: none; }
%(S)s ul { list-style: none; }
"""

NEUTRALIZER = """
/* ---- the host page's own rules stop here ---------------------------------
   THIS BLOCK IS LOAD-BEARING. These pages were built before this chrome existed
   and they use the same class names: aspire, identity and nobi each define their
   own .footer, and nobi defines .footer__legal. Their rules were landing on v3's
   markup -- aspire's `.footer { background: var(--navy) }` put a navy band across
   the bottom of the site footer, and nobi's `.footer__legal { color: var(--muted) }`
   painted the copyright line dark on dark until it disappeared.

   The scope class is doubled so this sits at (0,2,0): it beats any single-class
   rule a host page has, and loses to every rule below it in this file, which is
   also (0,2,0) but comes later. So it wipes the host's declarations and then v3's
   own put back exactly what belongs. Placed FIRST for that reason. */
%(S)s%(S)s *,
%(S)s%(S)s *::before,
%(S)s%(S)s *::after {
  background: none;
  border: 0;
  box-shadow: none;
  text-shadow: none;
  color: inherit;
  opacity: 1;
  filter: none;
  transform: none;
  animation: none;
  float: none;
  position: static;
  min-height: 0;
  max-width: none;
  text-align: inherit;
  text-transform: none;
  font-style: normal;
  font-variant: normal;
}
"""

BANNER = """/* ============================================================================
   THE SITE %(WHAT)s, for pages that do not load v3's global stylesheets
   ----------------------------------------------------------------------------
   v3's own rules, not a re-creation. Amanda: "Why not just use the existing one
   to keep the consistency."

   The project pages cannot load v3's styles.css: it carries a global reset and
   would restyle five hand-built pages. So the rules are scoped under %(S)s
   instead, and the tokens they read are redeclared there rather than on :root.
   Same declarations, same measured numbers, no leakage.

   The scope class goes on a WRAPPER, never on the component's own root element:
   every rule here is scoped as a DESCENDANT, and a descendant selector does not
   match the element carrying the class.

   Rules are collected BY SELECTOR from the whole of each source file, not from
   one banner-delimited block -- v3 keeps its mobile overrides in a shared @media
   block far from the component they belong to, and missing them is how the
   footer headline came to overflow a phone.

   The blocks are in v3's own load order -- styles.css, type-system.css,
   chrome.css -- because that order decides the winner between two equally
   specific single-class rules.

   GENERATED by scripts/gen-master-chrome.py. Regenerate; do not hand-edit.
   ========================================================================== */
%(S)s {
%(TOKENS)s

  /* from styles.css's body rule, which these components inherit from on v3 */
  font-family: "Figtree", system-ui, -apple-system, "Segoe UI", sans-serif;
  color: var(--black-1);
  line-height: 1.2;
  letter-spacing: -0.01em;
  -webkit-font-smoothing: antialiased;
  text-rendering: optimizeLegibility;
}
"""

TAIL = """

/* ---- the wrapper must not exist as a box --------------------------------
   .header is position: sticky, and a sticky element only travels inside its
   own containing block. A plain wrapper div is exactly as tall as the header,
   so the header would unstick the instant it had scrolled its own height --
   which is to say, never stick at all. display: contents removes the wrapper's
   box while leaving it in the DOM, so the descendant selectors above still
   match and the header sticks against the page. Amanda: "Keep the top-navbar
   always visible on top of the screen." */
.master-header { display: contents; }

/* ---- the reading progress bar -------------------------------------------
   v3's header carries the same element the case studies do, but its rules live
   in v1's css/case-study.css, which the Hazen page does not load. They are
   restated here, WIDTH-driven rather than transform-driven: case-study.js
   animates scaleX, and Hazen's own chrome script sets style.width. This file is
   only ever loaded by Hazen, so it follows Hazen's script. */
.master-header .cs-progress {
  position: absolute;
  left: 0;
  right: 0;
  bottom: 0;
  height: 3px;
  z-index: 101;
  pointer-events: none;
}
.master-header .cs-progress__bar {
  display: block;
  height: 100%;
  width: 0;
  background: var(--black-1);
}
"""

JOBS = [
    dict(out="master-footer.css", scope=".master-footer", what="FOOTER",
         classes=["container", "contact", "footer", "social", "copy-icon", "copy-toast"],
         types=True),
    dict(out="master-header.css", scope=".master-header", what="HEADER",
         classes=["container", "header", "nav", "nav-toggle", "mobile-menu",
                  "ext-arrow", "cs-progress"],
         types=False, tail=TAIL),
]

for job in JOBS:
    S = job["scope"]
    parts = [BANNER % {"WHAT": job["what"], "S": S, "TOKENS": root_tokens},
             RESET % {"S": S},
             NEUTRALIZER % {"S": S},
             "\n/* ==== styles.css ========================================================= */\n",
             scope(collect(styles, job["classes"]), S)]
    if job["types"]:
        parts += ["\n\n/* ==== type-system.css, entire ============================================ */\n",
                  scope(types, S)]
    parts += ["\n\n/* ==== chrome.css ========================================================= */\n",
              scope(collect(chrome, job["classes"]), S)]
    parts += [job.get("tail", ""), "\n"]
    text = reflow("".join(parts))
    (CSS / job["out"]).write_text(text)
    print(job["out"], "->", len(text), "bytes,", text.count("{"), "braces")
